amqp:
  admin:
      auto-create: true
  host: rabbitmq
  port: 5672
  username: admin_videos
  password: 123456

mysql:
  url:
  username:
  password:

spring:
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration