amqp:
  admin:
      auto-create: ${AMQP_ADMIN_AUTO_CREATE:false}
  host: ${AMQP_HOST:localhost}
  port: ${AMQP_PORT:5672}
  username: ${AMQP_USERNAME:admin_videos}
  password: ${AMQP_PASSWORD:123456}

mysql:
  url: ${MYSQL_URL:jdbc:mysql://db:3306/admin_catalogo?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8}
  username: ${MYSQL_USERNAME:root}
  password: ${MYSQL_PASSWORD:root}

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none