version: '3.9'

networks:
  codeflix-network:
    driver: bridge

services:
  app:
    image: ubuntu:latest
    networks:
      - codeflix-network
    depends_on:
      - db

  db:
    container_name: admin-catalogo-db
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=admin_catalogo
    ports:
      - 3306:3306
    networks:
      - codeflix-network
    volumes:
      - admin-catalogo-db:/var/lib/mysql

  rabbitmq:
    container_name: admin-videos-rabbitmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-admin_videos}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-123456}
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - codeflix-network

volumes:
  admin-catalogo-db:
    driver: local
