version: '3.9'

networks:
  codeflix-network:
    driver: bridge

services:
  app:
    image: ubuntu:latest
    networks:
      - codeflix-network
    depends_on:
      - db

  db:
    container_name: admin-catalogo-db
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=admin_catalogo
    ports:
      - 3306:3306
    networks:
      - codeflix-network
    volumes:
      - admin-catalogo-db:/var/lib/mysql

volumes:
  admin-catalogo-db:
    driver: local
