name: CI/CD Pipeline

on: 
    push: 
        branches: 
            - main
            - develop
            - 'hotfix/**'
            - 'release/**'
    workflow_dispatch: 

env:
    BUILD_TAG:
    IMAGE_NAME: allissonabn/fc3-admin-catalogo-api

jobs:
    # Job para a execução dos testes
    tests:
        name: Tests runner
        runs-on: ubuntu-latest
        # Configuração dos passos do job
        steps:
            # Checkout do código
            - uses: actions/checkout@v4
            # Configurar a JDK na máquina
            - name: Set up JDK@17
              uses: actions/setup-java@v4
              with:
                  java-version: 17
                  distribution: temurin
            # Executar os testes da aplicação
            - name: Run application tests
              run: ./gradlew test

    # Job para compilar a aplicação
    build:
        name: Build runner
        needs: tests
        runs-on: ubuntu-latest
        # Configuração dos passos do job
        steps:
            # Checkout do código
            - uses: actions/checkout@v4
            # Configurar a JDK na máquina
            - name: Set up JDK@17
              uses: actions/setup-java@v4
              with:
                  java-version: 17
                  distribution: temurin
            # Valida a existência do gradle wrapper
            - name: Validate Gradle Wrapper
              uses: gradle/actions/wrapper-validation@v3
            # Setup do Gradle
            - name: Setup Gradle 7.6
              uses: gradle/actions/setup-gradle@v3
              with:
                gradle-version: 7.6
            # Build da aplicação
            - name: Build application
              run: gradle clean build -x test
            # Definir variável branch name
            - name: Set BUILD_TAG
              run: |
                echo BUILD_TAG=$(echo ${{ github.head_ref || github.ref_name }} | sed "s,/,_,g")-${{ github.run_number }} >> $GITHUB_ENV
            # Print BUILD_TAG defined
            - name: Set BUILD_TAG
              run: |
                echo "Branch     ---> ${{ github.head_ref || github.ref_name }}"
                echo "Run number ---> ${{ github.run_number }}"
                echo "Tag        ---> ${{ env.BUILD_TAG }}"
            # Print BUILD_TAG defined
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USER }}
                  password: ${{ secrets.DOCKER_HUB_PWD }}
            # Build & Deploy Image
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                build-args: VERSION=${{ env.BUILD_TAG }}
                tags: ${{ env.IMAGE_NAME }}:${{ env.BUILD_TAG }}
