name: CI Pipeline

on:
    push: 
        branches: 
            - 'feature/**'
            - 'bugfix/**'
    # Habilita o gatilho manual através da interface do Github Actions
    workflow_dispatch: 

jobs:
    # Job para a execução dos testes
    tests:
        name: Tests runner
        runs-on: ubuntu-latest
        # Configuração dos passos do job
        steps:
            # Checkout do código
            - uses: actions/checkout@v4
            # Configurar a JDK na máquina
            - name: Set up JDK@17
              uses: actions/setup-java@v4
              with:
                  java-version: 17
                  distribution: temurin
            # Executar os testes da aplicação
            - name: Run application tests
              run: ./gradlew test
